### ISSUE TITLE
Sportradar.OddsFeed.SDK.Messages.XmlSerializers project under .NEZ is missing

### ISSUE THREAD

**Issue by heinrichelsigan** [sportradar/UnifiedOddsSdkNet#1]
When downloading and trying to build .NET solution, especifically Sportradar.OddsFeed.SDK.Entities.REST project, I 've a missing reference to Sportradar.OddsFeed.SDK.Messages.XmlSerializers.

Kind regards,
Heinrich Elsigan.

**Comment by dhrovat** [comment]
Hi,

we have added it yesterday. Try to pull it down and rebuild.

David

On 4 Mar 2019, at 12:05, Heinrich Elsigan <notifications@github.com<mailto:notifications@github.com>> wrote:


When downloading and trying to build .NET solution, especifically Sportradar.OddsFeed.SDK.Entities.REST project, I 've a missing reference to Sportradar.OddsFeed.SDK.Messages.XmlSerializers.

Kind regards,
Heinrich Elsigan.

**Comment by jpwits** [comment]
Also need help on this, I have now cloned both sdk projects and compiled them, but don't get a Sportradar.OddsFeed.SDK.XmlSerializers.dll, it keeps on giving me an error on the test

**Comment by jpwits** [comment]
also get this Sportradar.OddsFeed.SDK.Docs is an incompatible project in VS 2019, installed EWSoftware but this did not help
