### ISSUE TITLE
When RMQ recovers and API is still down, SDK waits for recovery to timeout before initiating another request 

### ISSUE THREAD

**Issue by anthonyersen** [sportradar/UnifiedOddsSdkNet#10]
Hi,

I've noticed that the recovery operation called in [ProducerRecoveryManager.ProcessSystemMessage()](https://github.com/sportradar/UnifiedOddsSdkNet/blob/0d56f14b14c6c740399e0470312d18b79d8763b5/src/Sportradar.OddsFeed.SDK.API/Internal/ProducerRecoveryManager.cs#L333) would return `true` when the API is down.

Digging into it, it seems like the recovery endpoint is called in [`LogHttpDataFetcher.PostDataAsync()`](https://github.com/sportradar/UnifiedOddsSdkNet/blob/0d56f14b14c6c740399e0470312d18b79d8763b5/src/Sportradar.OddsFeed.SDK.Entities.REST/Internal/LogHttpDataFetcher.cs#L191). But when this call throws an `HttpRequestException`, the [`RecoveryRequestIssuer` would just ignore it](https://github.com/sportradar/UnifiedOddsSdkNet/blob/0d56f14b14c6c740399e0470312d18b79d8763b5/src/Sportradar.OddsFeed.SDK.API/Internal/RecoveryRequestIssuer.cs#L195) and return the `requestNumber` anyway. This would cause [`RecoveryOperation.Start()`](https://github.com/sportradar/UnifiedOddsSdkNet/blob/0d56f14b14c6c740399e0470312d18b79d8763b5/src/Sportradar.OddsFeed.SDK.API/Internal/RecoveryOperation.cs#L219) to return `true` and eventually [set the recovery status in `ProducerRecoveryManager.ProcessSystemMessage()` to `ProducerRecoveryStatus.Started`](https://github.com/sportradar/UnifiedOddsSdkNet/blob/0d56f14b14c6c740399e0470312d18b79d8763b5/src/Sportradar.OddsFeed.SDK.API/Internal/ProducerRecoveryManager.cs#L336).

It wouldn't be until the recovery times out and [the check in `ProducerRecoveryManager.CheckStatus()`](https://github.com/sportradar/UnifiedOddsSdkNet/blob/0d56f14b14c6c740399e0470312d18b79d8763b5/src/Sportradar.OddsFeed.SDK.API/Internal/ProducerRecoveryManager.cs#L463) will the recovery endpoint be called again during the next alive message.

The recovery timeout value is set to [`producer.stateful_recovery_window_in_minutes`](https://github.com/sportradar/UnifiedOddsSdkNet/blob/0d56f14b14c6c740399e0470312d18b79d8763b5/src/Sportradar.OddsFeed.SDK.Messages/REST/MarketDescriptionMessages.cs#L450) which I think is 10 minutes.

**Comment by shanonbeary** [comment]
@dhrovat Have you had a chance to investigate? Were having issues with this as-well

**Comment by dhrovat** [comment]
Checking ...

**Comment by dhrovat** [comment]
This is now fixed. Will be available in next release.
Thank you,
David

**Comment by dhrovat** [comment]
Release (including this) is planned for later today.
