### ISSUE TITLE
CacheItemNotFoundException wrapped around CommunicationException

### ISSUE THREAD

**Issue by shanonbeary** [sportradar/UnifiedOddsSdkNet#14]
Hi,

We've received a CacheItemNotFoundException running in production:

`Sportradar.OddsFeed.SDK.Common.Exceptions.CacheItemNotFoundException: An error occurred while fetching competitor profile not found in cache ---> Sportradar.OddsFeed.SDK.Common.Exceptions.CommunicationException: Failed to execute http get ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 91.201.213.244:443`

It is hiding the fact that there is a communication exception. I've noticed here: https://github.com/sportradar/UnifiedOddsSdkNet/blob/20fe61dfc4253eca7b24469422d53be0203ede6c/src/Sportradar.OddsFeed.SDK.Entities.REST/Internal/Caching/Profiles/ProfileCache.cs#L156  On either CommuncationException, DeserializartionException or MappingException, it will throw a CacheItemNotFoundException, ideally it will surface the inner exception up to the caller. For our case that we will retry on CommuncationException, but it is hidden behind CacheItemNotFoundException which we would not retry. It be good if the Communication exception will be surfaced up.

**Comment by dhrovat** [comment]
True. It was changed now and will be available in next release.
