### ISSUE TITLE
Add support for cancellation of async / api calls

### ISSUE THREAD

**Issue by deuko** [sportradar/UnifiedOddsSdkNet#15]
Hey guys,

we noticed that unfortunately it is not possible to pass a CancellationToken into any async method for retrieving SportEvent-data (from any ISportEvent REST-entity like IMatch, ITournament, etc.)

Would it be possible to add overloads that takes and handles a CancellationToken for these methods to provide a clean way to correctly terminate pending requests (in case they query the API and for whatever reason the call takes longer than expected and we want to terminate it after our own time limit)?

Thank you in advance!

**Comment by dhrovat** [comment]
Hi,
new configuration options are planned to address custom timeouts for API calls. Will be available in next release.
Tnx
