### ISSUE TITLE
Permanent failure to open connection

### ISSUE THREAD

**Issue by gruntster** [sportradar/UnifiedOddsSdkNet#16]
## Expected Behaviour ##
Every time `Feed.Open` is invoked, it should attempt to open a connection unless a connection has already been successfully established.

## Current Behaviour ##
Only the first call to `Feed.Open` attempts to establish a connection. If the first attempt fails then all subsequent calls will fail regardless.

We're using SDK version 1.23.1.0.

Below are the errors that were logged when our system attempted to open a connection while the Betradar UOF message queue was down.

**First attempt:**
```
Sportradar.OddsFeed.SDK.Common.Exceptions.CommunicationException: Connection to the message broker failed, Probable Reason={Invalid or expired token} ---> System.IO.IOException: connection.start was never received, likely due to a network timeout
   at RabbitMQ.Client.Framing.Impl.Connection.StartAndTune()
   at RabbitMQ.Client.Framing.Impl.Connection.Open(Boolean insist)
   at RabbitMQ.Client.Framing.Impl.Connection..ctor(IConnectionFactory factory, Boolean insist, IFrameHandler frameHandler, String clientProvidedName)
   at RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.Init(AmqpTcpEndpoint endpoint)
   at RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.Init(IList`1 endpoints)
   at RabbitMQ.Client.ConnectionFactory.CreateConnection(IList`1 endpoints, String clientProvidedName)
   --- End of inner exception stack trace ---
   at Sportradar.OddsFeed.SDK.API.Feed.Open() Url=mq.ap-northeast-1.betradar.com:5671, Code=0, Response=
```

**All subsequent attempts:**
```
System.InvalidOperationException: Current OddsFeedSession is already opened
   at Sportradar.OddsFeed.SDK.API.Internal.EntityDispatcher`1.Open()
   at Sportradar.OddsFeed.SDK.API.Feed.Open()
```

This issue has been raised previously but not fully resolved: https://github.com/sportradar/UnifiedOddsSdkNet/issues/7

There are several checks in the SDK to prevent the opening of a connection when a connection has already been established. However these checks don't appear to reset themselves when the Open operation fails. For example:
* https://github.com/sportradar/UnifiedOddsSdkNet/blob/master/src/Sportradar.OddsFeed.SDK.API/Internal/EntityDispatcher.cs#L184
* https://github.com/sportradar/UnifiedOddsSdkNet/blob/master/src/Sportradar.OddsFeed.SDK.API/Internal/FeedRecoveryManager.cs#L268
* https://github.com/sportradar/UnifiedOddsSdkNet/blob/master/src/Sportradar.OddsFeed.SDK.API/Internal/SystemFeedSession.cs#L251

**Comment by anthonyersen** [comment]
Hi @dhrovat, we've encountered this issue as well when trying to reopen the `OddsFeed`. Will this be addressed?

**Comment by anthonyersen** [comment]
Also, `Feed.Open` would call `ProducerManager.Lock()` and not reset when it fails to connect. This blocks us from modifying the producer such as calling `ProducerManager.AddTimestampBeforeDisconnect()`

**Comment by dhrovat** [comment]
Hi,

sorry for late response. There were some improvements implemented to address issues mentioned. They will be available in next release.

Tnx.
