### ISSUE TITLE
English string is returned as a fallback for names that have no translation

### ISSUE THREAD

**Issue by deuko** [sportradar/UnifiedOddsSdkNet#19]
Hey!

we recently noted (for newly created Outright bet names - but I believe it's the same for all other names as well) that if you query any name-method (we noticed for IMarket.GetNameAsync()) with a CultureInfo, that has not been translated yet (in our case German), the default English string is returned. This is somewhat problematic, because we can not detect if the fallback-string is returned or the correctly translated one. Personally I would have expected that null / an empty string is returned if no translation is present - because I explicitly call that method with a specific CulturInfo.

I am aware that this is a fallback behavior and changing this would most likely cause problems to users that probably rely on that behavior. 
So my question is rather if something can be added that would only give me the specified translation or nothing, or some sort of mechanism to determine what the language of the received translation is (changing the return type to a key-value pair with CultureInfo or something)

Thank you in advance

**Comment by dhrovat** [comment]
Unfortunately this is the way Sport API works. Sdk only exposes what is received.
