### ISSUE TITLE
Translation of ordinal number in market descriptions

### ISSUE THREAD

**Issue by rolandothedev** [sportradar/UnifiedOddsSdkNet#20]
Hi,

Some markets have an ordinal number in their descriptions but these are not translated (at least not for the Spanish/Portuguese) languages.

Sample markets:

- "When will the Xth goal be scored (10 min interval)" Examples:
  - Current Spanish market description: "Cuándo el 1st gol se marcará (intervalo 10 min)"
  - Expected Spanish market description: "Cuándo el 1º gol se marcará (intervalo 10 min)"
 
  - Current Portuguese market description: "Quano será marcado o 1st golo (intervalo de 10 minutos)"
  - Expected Portuguese market description: "Quano será marcado o 1º golo (intervalo de 10 minutos)"

- "Xth half, Xth goal" Examples:
  - Current Spanish market description: "1º Mitad - 1st gol"
  - Expected Spanish market description: "1º Mitad - 1º gol"
  
  - Current Portuguese market description: "1ª parte - 1st golo"
  - Expected Portuguese market description: "1ª parte - 1º golo"

- "Xth half - Xth corner"

Thanks in advance for looking into this.
@dhrovat

**Comment by dhrovat** [comment]
Hi,
tested in both normal and core versions and in current version it seems ok.
