### ISSUE TITLE
Will Core 3.0 be supported in the future?

### ISSUE THREAD

**Issue by Malavos** [sportradar/UnifiedOddsSdkNet#5]
With the [incoming .net core 3.0](https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0), and the previews being generally avaliable, it begs the question: Will .net core 3.0 be supported?

The RC is scheduled to be released in [July](https://github.com/dotnet/core/blob/master/roadmap.md). I know it's a bit early, but we are doing some planning what SDK we should use.

Thank you!

**Comment by shanonbeary** [comment]
@dhrovat Would you guys be able to answer this?

**Comment by dhrovat** [comment]
Hi,
we are discussing supporting sdk version with .NET Core 3.0, or rather .NET Standard 2.1. At the moment there is no date yet, but the first version could be available by the end of the August.

**Comment by Malavos** [comment]
@dhrovat  thank you. That's good to know. We will have enough time to make other things while we wait August/September to come. I will now close the issue.
