### ISSUE TITLE
Strange check during Open method of Feed class

### ISSUE THREAD

**Issue by hajin-song** [sportradar/UnifiedOddsSdkNet#7]
Hi,

I've noticed that in `Open` method of `Feed` class, [it is checking and setting a flag to determine whether the feed is already open or not](https://github.com/sportradar/UnifiedOddsSdkNet/blob/master/src/Sportradar.OddsFeed.SDK.API/Feed.cs#L486).

While using the SDK, I ran into scenarios where `Open` would fail half way through and next time `Open` is called on same `Feed` instance, an exception will be thrown saying `The feed is already opened`.

Was this the intended behaviour? Do we need to recreate the instace of `Feed` object everytime it fails to open the feed? Shouldn't the `Feed` instance be expected to be able to retry until it can open the feed?

**Comment by dhrovat** [comment]
Hi,
thank you for pointing this out. You are correct. The reset on exception was added.

**Comment by shanonbeary** [comment]
@dhrovat Thanks for the quick response.
