### ISSUE TITLE
Feed class constructor seems to be violating Microsoft standard

### ISSUE THREAD

**Issue by hajin-song** [sportradar/UnifiedOddsSdkNet#9]
Hi,

I've noticed that `Feed` class [seems to be doing extra work on top of capturing the constructor parameters](https://github.com/sportradar/UnifiedOddsSdkNet/blob/master/src/Sportradar.OddsFeed.SDK.API/Feed.cs#L168).

According to the [MS Constructor Design document](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/constructor), class constructor should only capture the parameter being passed into.

The current way of implementing the constructor can cause issue when unavailable or invalid Betradar endpoint is given as `whoami` check is being done at constructor time. A failure to the `whomai` call will cause exception being thrown at constructor level. This behaviour is quite disruptive if you are using DI to inject `IOddsFeed` type object as singleton.

Would it be possible to refactor the `Feed` constructor to split the initialisation process out of the  constructor?

**Comment by dhrovat** [comment]
This was now rewritten. Will be available in next release. TY.

**Comment by shanonbeary** [comment]
@dhrovat Thanks for the quick response
